[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common_lib = { path = "../common_lib" }
log = "0.4.29"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.102"
bincode = "1.3"
chrono = "0.4.44"
fern = "0.7.1"
