[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
common_lib = { path = "../common_lib" }
rand = "0.9"
log = "0.4"
env_logger = "0.11"
crossbeam-channel = "0.5"
bincode = "1.3"
